# Human readable title of application.
title: Template Provider

overviewShort: The Template Crossplane Provider allows you to bootstrap your own provider.
overview: |-
  
# Markdown description of this entry
readme: |
 

# Maintainer names and emails.
maintainers:
- name: Dan Mangum
  email: dan@upbound.io

# Owner names and emails.
owners:
- name: Dan Mangum
  email: dan@upbound.io

# Human readable company name
company: Crossplane

# Primary category describing this stack
category: Infrastructure

# Type of package: Provider, Stack, or Application
packageType: Provider

# Keywords that describe this application and help search indexing
keywords:
- "template"
- "infrastructure"

# Links to more information about the application (about page, source code, etc.)
website: "https://crossplane-book.github.io"
source: "https://github.com/crossplane-book/provider-template"

# RBAC ClusterRoles will be generated permitting this stack to use all verbs on all
# resources in the groups listed below.
permissionScope: Cluster
dependsOn:
- crd: '*.cache.crossplane.io/v1alpha1'
- crd: '*.compute.crossplane.io/v1alpha1'
- crd: '*.database.crossplane.io/v1alpha1'
- crd: '*.core.crossplane.io/v1alpha1'
- crd: '*.storage.crossplane.io/v1alpha1'
- crd: '*.workload.crossplane.io/v1alpha1'

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0